### ISSUE TITLE
 issue with arm systems  

### ISSUE THREAD

**Issue by wima88** [gbmhunter/CppLinuxSerial#9]
[full_error_report.txt](https://github.com/gbmhunter/CppLinuxSerial/files/5836976/full_error_report.txt)
Hello , first of all thank you for the well organized library 

when using directly with a main program (main.cpp) library works as intended  without any issues , how ever when try to create a class using  static library(libCppsearial.a) following error occurs when linking 
 
/usr/bin/ld: /usr/local/lib/libCppLinuxSerial.a(SerialPort.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN2mn14CppLinuxSerial10SerialPortE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libCppLinuxSerial.a(SerialPort.cpp.o): In function `mn::CppLinuxSerial::SerialPort::SerialPort()':
SerialPort.cpp:(.text+0x10): dangerous relocation: unsupported relocation

kernel version bionic

**Comment by AmaurX** [comment]
Hello

I had a very similar issue, on a raspberrypi, where my main program would compile when linking against CppLinuxSerial, but upon execution I would get a error : 
``` error while loading shared libraries: my/share/library.so.8: unexpected reloc type 0x03 ```
After investigation, it was happening to the very same symbol you are having issues with.

Turns out your comment helped me. I add the line 
``` SET(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -fPIC") ``` 
to the src/CmakeList.txt, recompiled everything and it worked fine. 

I hope that helps!

**Comment by wima88** [comment]
Yep ! that solves it ,Thanks AmaurX
